### ISSUE TITLE
Document Optical Hardware Requirements

### ISSUE THREAD

**Issue by peterGarate** [peterGarate/Social_Robotics_1#5]
Write up a word document that includes your requirements data and specifications related to the optical hardware, methods of use, and associated software. Use a table format for specifications (numbers, ranges, approx numbers).
Keep the customer's needs in mind as discussed with our sponsor.

**Typical Outline for a Requirements Specification**
1. Overview
2. Statement of the problem
3. Operational description (draft user's manual)
4. Requirements Specification
5. Design analysis
6. Preliminary system test plan
7. Implementation considerations
    - Service and maintenance
    - Manufacture

**Attachments**
A Studies (lab reports or marketing studies, for example
B Relevant codes and standards

**Areas to consider when writing your document (relate this to optical hardware)**
- Is the customer knowledgeable or frontier
- What are the boundaries?
- Camera Standards
- Size (Quantity)
- Location (placement of cameras)
- Power
- Operating conditions/life
- Highlight conflicting needs
- List Real-World considerations
- Real-World Influences to specifications
- Input/Output analysis
- Preview Interface (Software GUI perhaps?)
- Survey design attributes

**Comment by wrobeljm** [comment]
[Optical Camera Requirements.docx](https://github.com/peterGarate/Social_Robotics_1/files/5682686/Optical.Camera.Requirements.docx)
