### ISSUE TITLE
Document Machine Learning Requirements

### ISSUE THREAD

**Issue by peterGarate** [peterGarate/Social_Robotics_1#7]
Write up in a word document your machine learning requirements/specs to include your data presented in the presentation to the class. Then upload that document to this issue. Use a table format for specifications (numbers, ranges, approx numbers).

**Typical Outline for a Requirements Specification**
1. Overview
2. Statement of the problem
3. Operational description (draft user's manual)
4. Requirements Specification
5. Design analysis
6. Preliminary system test plan
7. Implementation considerations
    - Service and maintenance
    - Manufacture

**Attachments**
A Studies (lab reports or marketing studies, for example
B Relevant codes and standards

**Areas to consider for writing your document (relate to machine learning only)**
- Is the customer knowledgeable or frontier
- What are the boundaries of Machine Learning
- Machine Learning Standards
- Size - Computer Requirements for running machine learning software and code.
- Location - Where will the machine learning be located (computer, robot, cloud, all three?)
- Power - Computer hardware requirements needed.
- Operating conditions/life
- Highlight conflicting needs
- List Real-World considerations
- Real-World Influences to specifications
- Input/Output analysis
- Preview Interface
- Survey design attributes

**Comment by efeller1552** [comment]
[MachineLearningRequirements.docx](https://github.com/peterGarate/Social_Robotics_1/files/5670046/MachineLearningRequirements.docx)

I tried to hit all of the points. May have gone too into the "how" with some things but figured it would be better to add it and delete later. Let me know if there is anything else I should research or if I should re-write this with better formatting. If I should add more numbers/information I can do that as well

**Comment by peterGarate** [comment]
> 
> 
> [MachineLearningRequirements.docx](https://github.com/peterGarate/Social_Robotics_1/files/5670046/MachineLearningRequirements.docx)
> 
> I tried to hit all of the points. May have gone too into the "how" with some things but figured it would be better to add it and delete later. Let me know if there is anything else I should research or if I should re-write this with better formatting. If I should add more numbers/information I can do that as well

Thank you Emily, I will take a look and incorporate your work ASAP. If anything else is needed, I will either reopen this issue or start a new one for better visibility.
