### ISSUE TITLE
Document Constraint and High Level Software Requirements

### ISSUE THREAD

**Issue by peterGarate** [peterGarate/Social_Robotics_1#8]
Write up a word document on your requirements/specs that you presented in class. This includes the high level software requirements and constraints on the project and team. Once you've written up your portion of the requirements, upload the word document to this issue. Use a table format for specifications (numbers, ranges, approx numbers).

**Areas to consider**
- Is the customer knowledgeable or frontier
- What are the boundaries of the project
- Weight
- Standards
- Size
- Location
- Power
- Operating conditions/life
- Highlight conflicting needs
- List Real-World considerations
- Real-World Influences to specifications
- Input/Output analysis
- Preview Interface? (Pictures of 3D model)
- Survey design attributes

**Comment by ben-nm11** [comment]
[HLR_Constraints.docx](https://github.com/peterGarate/Social_Robotics_1/files/5649449/HLR_Constraints.docx)
